server:
  port: 8888
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: skill-service
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/skills/**

        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/position/**