spring:
  config:
    import: configserver:http://localhost:8089
  application:
    name: GATEWAY-SERVICE
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: profiler-security
            scope: openid
            authorization-grant-type: password
            client-secret: FefCyUWfCEa3qFcjwgbAFUoRdvXtiRm7
        provider:
          keycloak:
            token-uri: https://localhost:8080/realms/profiler/protocol/openid-connect/token
            issuer-uri: http://localhost:8080/realms/profiler/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: skill-service
          uri: lb://SKILL-SERVICE
          predicates:
            - Path=/skills/**

        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/position/**

#        - id: identity-service
#          uri: lb://IDENTITY-SERVICE
#          predicates:
#            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

logging:
  level:
    org.springframework.security: trace